services:
  mongodb:
    image: 'mongo'
    ports:
      - "27017:27017"
    labels:
      - com.prometheus.scrape=true
      - com.prometheus.port=9100
    volumes:
      - data:/data/db


  backend:
    image: saurabhdave59/mern-backend:latest
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
      - JWT_SECRET= ${jwt}
    depends_on:
      - mongodb
    hostname: mybackendhostname
    labels:
      - com.prometheus.scrape=true
      - com.prometheus.port=8000
    

  mongodb-expoter:
    image: bitnami/node-exporter:latest
    environment:
      - MONGODB_URI=${mongo_uri}
    ports:
      - "9100:9100"
    deploy:
      resources:
        limits:
          memory: 128M
    hostname: mymongodb
    depends_on:
      - mongodb
  
  prometheus:
    image: "prom/prometheus" 
    ports:
      - "9090:9090"  
    volumes:
      - ./prometheus:/etc/prometheus  
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  
    deploy:
      resources:
        limits:
          memory: 1G
    depends_on:
      - backend
      - mongodb

  grafana:
     image: grafana/grafana
     ports:
       - "3001:3000"
     volumes:
       - grafana_data:/var/lib/grafana   # Named volume, not host bind
     environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DATASOURCES_PROMETHEUS_URL=http://prometheus:9090
     depends_on:
      - prometheus
     deploy:
      resources:
        limits:
         memory: 1G
     labels:
       - com.prometheus.scrape=true
       - com.prometheus.port=8000

  frontend:
    image: saurabhdave59/mern-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - BACKEND_HOST=backend
    hostname: myfrontendhostname
    depends_on:
      - backend
volumes:
  data:
  grafana_data:
  