name: Build and Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push backend image
    - name: Build and push backend
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mern-backend ./mern-todo-app/backend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/mern-backend

    # Build and push frontend image
    - name: Build and push frontend
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mern-frontend ./mern-todo-app/frontend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/mern-frontend

    # Build and push main/root image
    - name: Build and push root
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mern-root ./mern-todo-app
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/mern-root

    # Deploy on EC2 using docker-compose
    - name: SSH into EC2 and deploy with docker-compose
      uses: appleboy/ssh-action@master
      with:
        debug: true
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/app   # make sure docker-compose.yml is here
          
          # pull latest images
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mern-backend
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mern-frontend
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mern-root
          
          # restart containers
          docker-compose down || true
          docker-compose up -d --build
